export enum ActionTypes {
  SET_AUTH_DATA = "SET_AUTH_DATA",
  SET_ERRORS = "SET_ERRORS",
  SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE",
  SET_IS_SUCCESS = "SET_IS_SUCCESS",
  SET_TOUCHED = "SET_TOUCHED",
}

export enum TripListActionTypes {
  SET_TRIPS = "SET_TRIPS",
  SET_LOADING = "SET_LOADING",
  SET_EDIT_TRIP_ID = "SET_EDIT_TRIP_ID",
  SET_OPEN_DROPDOWN_ID = "SET_OPEN_DROPDOWN_ID",
}
